# Generated by Django 5.0.7 on 2024-07-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='group',
            field=models.ManyToManyField(to='classs.class'),
        ),
    ]
