# Generated by Django 5.0.7 on 2024-07-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='group',
            new_name='classes',
        ),
        migrations.RemoveField(
            model_name='school',
            name='title',
        ),
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
