# Generated by Django 5.0.7 on 2024-07-10 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={},
        ),
        migrations.RenameField(
            model_name='class',
            old_name='Student',
            new_name='students',
        ),
        migrations.RemoveField(
            model_name='class',
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='class',
            name='title',
        ),
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
